export const SUDOKU_SOLVE = 'SUDOKU_SOLVE';
export const SUDOKU_SHUFFLE = 'SUDOKU_SHUFFLE';
export const SUDOKU_GET_MATCHING_ROW = 'SUDOKU_GET_MATCHING_ROW';
export const SUDOKU_GET_MATCHING_COL = 'SUDOKU_GET_MATCHING_COL';
export const SUDOKU_GET_MATCHING_BLOCK = 'SUDOKU_GET_MATCHING_BLOCK';